### ISSUE TITLE
Attribute selector does not work with :host selector

### ISSUE THREAD

**Issue by arodic** [Polymer/lit-element#1073]
Using CSS attribute selectors is very useful for various reasons. For example, you can show/hide elements and their children depending on attribute values. However, this hoes not work with `:host` selector using lit-element. For example, the following CSS should set element's background color to red, whenever red attribute is present:

```css
 :host[red] {
  background-color: red;
}
```

**Comment by arodic** [comment]
In fact, it looks like class selector does not work with `:host`. This also doesn't work:


```css
:host.red {
  background-color: red;
}
```
