### ISSUE TITLE
`css` tag function behaviour when (source map) comments are included

### ISSUE THREAD

**Issue by GHNewbiee** [Polymer/lit-element#1100]
In the following example, `styles.css` file includes only valid `CSS` literals and `cssStyles` is imported which also includes source map comments.

When using
```js
    return css`${unsafeCSS(cssStyles)}`;
```
everything is rendered ok.

But, without using `unsafeCSS()`, I see a blank screen.

**Q**: General speaking, are comments allowed within an imported `CSS` file?

*styles.css*
```css
.main {
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 2.2rem;
  text-align: center;
  font-family: sans-serif;
  color: white;
  background-color: #2a2938;
  padding: 20px;
}
```
*index.js*
```js
import { LitElement, customElement, css, unsafeCSS, html } from 'lit-element';
import cssStyles from './styles.css';

@customElement('my-element')
export class MyElement extends LitElement {
  static get styles() {
    return css`${unsafe(cssStyles)}`;
  }

  render() {
    return html`
      <div>${cssStyles}</div>
      <div class="main">
        <p>
          Get started by editing
          <code>src/index.js</code> and <code>public/index.html</code>
        </p>
      </div>
    `
  }
}
```
then **browser**, properly rendered, displays
```
/* src/styles.css */ .main { position: fixed; top: 0; left: 0; bottom: 0; right: 0; display: flex; justify-content: center; align-items: center; font-size: 2.2rem; text-align: center; font-family: sans-serif; color: white; background-color: #2a2938; padding: 20px; } /*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9zdHlsZXMuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIi5tYWluIHtcbiAgcG9zaXRpb246IGZpeGVkO1xuICB0b3A6IDA7XG4gIGxlZnQ6IDA7XG4gIGJvdHRvbTogMDtcbiAgcmlnaHQ6IDA7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xuICBmb250LXNpemU6IDIuMnJlbTtcbiAgdGV4dC1hbGlnbjogY2VudGVyO1xuICBmb250LWZhbWlseTogc2Fucy1zZXJpZjtcbiAgY29sb3I6IHdoaXRlO1xuICBiYWNrZ3JvdW5kLWNvbG9yOiAjMmEyOTM4O1xuICBwYWRkaW5nOiAyMHB4O1xufSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7QUFBQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSIsInNvdXJjZVJvb3QiOiJyZWJvb3N0Oi8vLyJ9 */

Get started by editing src/index.js and public/index.html
```
