### ISSUE TITLE
([hidden]) convention

### ISSUE THREAD

**Issue by Link2Twenty** [Polymer/lit-element#50]
In some of your examples, readme and demo, you have `display: block`, which is fine but, is it worth including hidden in these examples, just because it's good form?

```CSS
<style>
  :host {display: block;}
  :host([hidden]) {display: none;}
</style>
```

https://developers.google.com/web/fundamentals/web-components/best-practices#add-a-host-display-style-that-respects-the-hidden-attribute
